
        
       
		CREATE TABLE ADDRESS(
		ADDR_ID NUMBER(10) NOT NULL,
		LINE1 VARCHAR2(100) NOT NULL,
		LINE2 VARCHAR2(100),
		CITY VARCHAR2(50) NOT NULL,
		STATE VARCHAR2(50) NOT NULL,
		POSTAL_CD NUMBER(10) NOT NULL,
		ZONE VARCHAR2 (10),
		PRIMARY KEY (ADDR_ID)
		);
		
		CREATE TABLE ITEM(
		ITEM_ID NUMBER(10) NOT NULL,
		ITEM_NM VARCHAR2(200) NOT NULL,
		ITEM_DESC VARCHAR2(255),
		ITEM_PRICE NUMBER(5),
		PRIMARY KEY (ITEM_ID)
		);